#!/usr/bin/env ruby

SAFE_FILES_AND_PATHS = [
  '~',
  ''
].freeze

options = []
files = []

ARGV.each do |arg|
  # https://www.gnu.org/software/coreutils/manual/html_node/rm-invocation.html#rm-invocation
  # IF --, ALL REMAINING OPTIONS ARE NON ARGUMENTS!
  if arg.start_with?('--')
    files << arg
    # Otherwise, if an argument begins with -, it must be an option to pass to rm.
  elsif arg.start_with?('-')
    options << arg
  else
    files << arg
  end
end

# Checks if any of the file arguments passed to safe_rm are included in the safe list, ie, the user should be prompted before deleting them.
files.each do |file|
  if SAFE_FILES_AND_PATHS.include?(file)
    # The -i argument tells the rm command to prompt before deleting each file.
    # https://www.gnu.org/software/coreutils/manual/html_node/rm-invocation.html#rm-invocation
    options << '-i'
    break
  end
end
